name: dartson
version: 0.2.3
author: Eric Schneller <eric@schnellers.name>
description: Dartson is a Dart library that can be used to convert Dart objects into a JSON string. It uses dart:mirrors reflection to rebuild the schema. It also works in dart2js when using the dartson builder.
homepage: https://github.com/eredo/dartson
environment:
  sdk: '>=1.3.0'
dependencies:
  analyzer: ^0.27.4
  barback: ^0.15.2+9
  logging: ^0.11.3+1
  source_maps: ^0.10.1+1
  source_span: ^1.2.3
dev_dependencies:
  path: any
  test: any
